#!/bin/bash

apt-get update

# Install rgdal dependencies
sudo apt-get install -y libgdal-dev
sudo apt-get install -y gdal-bin
sudo apt-get install -y libproj-dev

# Install highcharter dependencies
sudo apt-get install -y libicu-dev
sudo apt-get install -y libglpk-dev
sudo apt-get install -y libgmp3-dev
sudo apt-get install -y libxml2-dev
sudo apt-get install -y libcurl4-openssl-dev
sudo apt-get install -y libssl-dev
sudo apt-get install -y zlib1g-dev
