#!/bin/bash

apt-get update

# Install rgdal dependencies
apt-get install -y libgdal-dev
apt-get install -y gdal-bin
apt-get install -y libproj-dev

# Install highcharter dependencies
apt-get install -y libicu-dev
apt-get install -y libglpk-dev
apt-get install -y libgmp3-dev
apt-get install -y libxml2-dev
apt-get install -y libcurl4-openssl-dev
apt-get install -y libssl-dev
apt-get install -y zlib1g-dev
