---
title: "Presentation title"
subtitle: "Presentation subtitle"
author: "Author Name"
institute: "NHS Organisation"
date: "Presentation Date"
output:
  xaringan::moon_reader:
    css: 
      - default
      - css/nhsr.css
      - css/nhsr-fonts.css
    lib_dir: libs
    seal: false
    nature:
      highlightStyle: googlecode
      highlightLines: true
      highlightLanguage: ["r"]
      countIncrementalSlides: false
      ratio: "16:9"
    includes:
      after_body: [css/insert-logo.html]
---

```{r setup, include = FALSE}
library(knitr)
library(tidyverse)
library(NHSRtheme)
library(emo)
# set default options
opts_chunk$set(echo = FALSE,
               fig.width = 7.252,
               fig.height = 4,
               dpi = 300)
```

class: title-slide, left, bottom

# `r rmarkdown::metadata$title`
----
### `r rmarkdown::metadata$author`
### `r rmarkdown::metadata$date`

---
name: reticulate
class: top,left

# What is {reticulate}?

The `{reticulate}` package provides a comprehensive set of tools for interoperability between Python and R. 

If your preferred choice of language is R and you are ready to make a jump to learn Python or vice versa. 

Link to [Reticulate](https://rstudio.github.io/reticulate/) package.

Link to [Reticulate cheatsheet](https://ugoproto.github.io/ugo_r_doc/pdf/reticulate.pdf).

---
name:overview
class:top,left

# Plan of today's session

--

* Load {mlbench} R library to pull diabetes data and run one of classic binary classification using Python in the R markdown!

--

* Setting up python environment by creating conda environment `conda_create(yourenv)`

  * Other ways of setting the Python environment using {`use_virtualenv()`, `mini_conda()`}
  
  * The `{reticulate}` package includes functions for creating Python environments(either virtualenvs or conda envs) and installing packages within them

--

* Install Python packages 

--

* Importing Python packages into R environment

--

* Creating logistic regression models to solve binary classification problem

  * We will load {data(PimaIndiansDiabetes)}
  
  * Use Python library `{scikit-learn}` to create binary classification model

---
name:end
class:top,left

# Check out few blogs

* I referenced NHSR webinar and Rstudio blog. 


* Link to [NHSR webinar](https://nhsrcommunity.com/learn-r/workshops/r-and-python-a-happy-union-with-reticulate/). If you haven't done it yet, please check out NHSR community too! `r emo::ji("+1")`

* Link to [Rstudio blog](https://rviews.rstudio.com/2019/03/18/the-reticulate-package-solves-the-hardest-problem-in-data-science-people/)

Thanks for joining me today! Happy coding! `r emo::ji("smile")`


