#channels:
#  - defaults
#  - conda-forge

#dependencies:
#  - requests=2.26.0
#  - pandas=1.3.2
#  - matplotlib=3.4.2
#  - seaborn=0.11.2
#  - numpy=1.20.3
#  - statsmodels=0.12.2
#  - scikit-learn=0.24.2
#  - scipy=1.7.1
#  - opencv=4.5.5
#  - msrest=0.6.21
#  - boto3=1.20.24
#  - pip
#  - pip:
#    - azure-cognitiveservices-vision-computervision==0.9.0
  
